### ISSUE TITLE
Síntesis 

### ISSUE THREAD

**Issue by Brendalp** [SistemasTecTlaxiaco/sintesis-Brendalp#2]
[Síntesis Buenas prácticas en Gestión de Proyectos.pdf](https://github.com/SistemasTecTlaxiaco/sintesis-Brendalp/files/7150518/Sintesis.Buenas.practicas.en.Gestion.de.Proyectos.pdf)

**Comment by Eva155** [comment]
Calificación: 20 PUNTOS 
Calificó: Eva Aguilar Avendaño

**Comment by josealfredo79** [comment]
Esta bien hecho...y revisado...
